### PR TITLE
Several updates

### PR DESCRIPTION
**Pull request by TheSnowfield**

### CODE REVIEW

**Review by takayama-lily — APPROVED** [review]

**Review by Yang-Fly — APPROVED** [review]
GOOOOOD

**Review by XxLittleCxX — APPROVED** [review]

**Comment by Misaka12456** [comment]
Nice

**Review by Misaka12456 — APPROVED** [review]
Nice

**Review by InariAimu — APPROVED** [review]
This is good.

**Review by Yang-Fly — APPROVED** [review]

**Pull request merged**
